-- ============================================================
-- Vigia Crypto - Colunas em falta (2026-08-13)
-- Colar no SQL Editor do Supabase e clicar em "Run"
-- Causa dos erros no site:
--   /alerts/holdings        -> column transacted_tokens.ai_analysis does not exist
--   /alerts/smart-money     -> column arkham_signals.id does not exist
--   /alerts/prelisting-*    -> column token_prelisting_wallets.classification does not exist
-- ============================================================

-- Widget Top100: o worker envia "ALTA"/"MEDIA" (texto) mas a coluna era numeric
alter table top100_technical_rankings alter column technical_confidence type text;

-- Widget Listings (transacted_tokens)
alter table transacted_tokens add column if not exists ai_analysis text;

-- Widget Smart Money (arkham_signals)
alter table arkham_signals add column if not exists id bigint generated by default as identity primary key;

-- Radar Smart Money / pre-listing wallets (token_prelisting_wallets)
alter table token_prelisting_wallets add column if not exists listing_ts timestamptz;
alter table token_prelisting_wallets add column if not exists classification text;
alter table token_prelisting_wallets add column if not exists investigation_status text;
alter table token_prelisting_wallets add column if not exists raw jsonb;
alter table token_prelisting_wallets add column if not exists pre_listing_out_usd numeric;
alter table token_prelisting_wallets add column if not exists post_listing_out_usd numeric;
alter table token_prelisting_wallets add column if not exists pre_listing_retention_pct numeric;
alter table token_prelisting_wallets add column if not exists post_listing_destinations jsonb;
alter table token_prelisting_wallets add column if not exists balance_usd numeric;

-- Confirmacao (deve listar as colunas)
select 'transacted_tokens' as tabela, string_agg(column_name, ',') as colunas
from information_schema.columns where table_name = 'transacted_tokens'
union all
select 'arkham_signals', string_agg(column_name, ',')
from information_schema.columns where table_name = 'arkham_signals'
union all
select 'token_prelisting_wallets', string_agg(column_name, ',')
from information_schema.columns where table_name = 'token_prelisting_wallets';
